### ISSUE TITLE
Restore hover-based hide/show of subsection permalinks

### ISSUE THREAD

**Issue by waldoj** [statedecoded/statedecoded#329]
I'm attempting to restore the pre-new-UI functionality of hiding and showing the permalink icon for each paragraph based on mouseovers. With the old design, it was as easy as this:

``` css
.law section a.section-permalink {
    visibility: hidden;
    text-decoration: none;
    color: #66c;
}
.law section:hover a.section-permalink {
    visibility: visible;
}
```

For whatever reason, this no longer works—the result is that the permalinks are never hidden. If I remove the `section:hover` bit, then the permalinks are, instead, always hidden. Figure out what's broken here and make it work. If all else fails, replace the CSS functionality with JavaScript. (And, if JavaScript does prove to be the solution, replace the link icon with an blank character of the same size, swapping out with the link icon on mouseover. That way, when copying the text out and pasting it into another document, every section won't have a link icon displayed at the end.)
