### ISSUE TITLE
Menu icons missing

### ISSUE THREAD

**Issue by waldoj** [statedecoded/statedecoded#481]
For no reason that I can quickly identify, menu icons aren't showing up on my local Vagrant instance:

![icons](https://f.cloud.github.com/assets/656758/1336813/0e4b9024-35cd-11e3-9076-0570b05dee22.png)

The images exist, and are specified in the CSS, e.g.:

``` css
header#page_header nav#main_navigation ul li a#browse {
  background-image:url('../images/nav-icons/nav_browse.svg?1381337771')
}
```

This needs to be investigated.
